services:
  jekyll:
    build: .
    container_name: al-folio-website
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    command: bundle exec jekyll serve --host 0.0.0.0
